import type { Product, Category, Brand } from "@/types";

export const mockCategories: Category[] = [
  { id: "1", name: "Chaussures Homme", slug: "chaussures-homme", is_active: true, sort_order: 1 },
  { id: "2", name: "Chaussures Femme", slug: "chaussures-femme", is_active: true, sort_order: 2 },
  { id: "3", name: "Vêtements Homme", slug: "vetements-homme", is_active: true, sort_order: 3 },
  { id: "4", name: "Vêtements Femme", slug: "vetements-femme", is_active: true, sort_order: 4 },
  { id: "5", name: "Électroniques", slug: "electroniques", is_active: true, sort_order: 5 },
  { id: "6", name: "PC & Accessoires", slug: "pc-accessoires", is_active: true, sort_order: 6 },
  { id: "7", name: "Accessoires Homme", slug: "accessoires-homme", is_active: true, sort_order: 7 },
  { id: "8", name: "Accessoires Femme", slug: "accessoires-femme", is_active: true, sort_order: 8 },
];

export const mockBrands: Brand[] = [
  { id: "1", name: "Nike", slug: "nike", is_active: true },
  { id: "2", name: "Adidas", slug: "adidas", is_active: true },
  { id: "3", name: "Apple", slug: "apple", is_active: true },
  { id: "4", name: "Samsung", slug: "samsung", is_active: true },
  { id: "5", name: "JBL", slug: "jbl", is_active: true },
  { id: "6", name: "Oraimo", slug: "oraimo", is_active: true },
];

export const mockProducts: Product[] = [
  {
    id: "1",
    category_id: "1",
    brand_id: "1",
    name: "Nike Air Max 270",
    slug: "nike-air-max-270",
    sku: "NK-AM270-001",
    main_image_url: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=70",
    short_description: "Sneaker lifestyle ultra-confortable avec la plus grande unité Air de Nike. Idéale pour une tenue décontractée ou sportive.",
    description: `La Nike Air Max 270 redéfinit le confort au quotidien avec son unité Air au talon de 32 mm, la plus grande jamais intégrée dans une chaussure lifestyle Nike. Sa tige mesh en Flyknit assure une légèreté et une respirabilité exceptionnelles, parfaites pour le climat chaud du Gabon.\n\nConçue pour vous accompagner du matin au soir, que ce soit dans les rues de Libreville ou lors de vos sorties du week-end. La semelle intermédiaire en mousse ultra-légère absorbe chaque impact et offre un rebond énergique à chaque foulée.\n\n**Pourquoi choisir la Nike Air Max 270 ?**\n- Confort toute la journée grâce à l'unité Air Max au talon\n- Tige respirante adaptée aux températures tropicales\n- Design moderne et polyvalent\n- Semelle en caoutchouc durable`,
    current_price: 65000,
    old_price: 85000,
    stock_quantity: 12,
    is_featured: true,
    is_new: false,
    is_promo: true,
    status: "active",
    rating: 4.5,
    review_count: 23,
    category: { id: "1", name: "Chaussures Homme", slug: "chaussures-homme", is_active: true, sort_order: 1 },
    brand: { id: "1", name: "Nike", slug: "nike", is_active: true },
    variants: [
      { id: "v1-1", product_id: "1", color: "Blanc / Rouge", size: "40", stock_quantity: 3, price_adjustment: 0 },
      { id: "v1-2", product_id: "1", color: "Blanc / Rouge", size: "41", stock_quantity: 2, price_adjustment: 0 },
      { id: "v1-3", product_id: "1", color: "Blanc / Rouge", size: "42", stock_quantity: 4, price_adjustment: 0 },
      { id: "v1-4", product_id: "1", color: "Blanc / Rouge", size: "43", stock_quantity: 1, price_adjustment: 0 },
      { id: "v1-5", product_id: "1", color: "Noir / Blanc", size: "40", stock_quantity: 2, price_adjustment: 0 },
      { id: "v1-6", product_id: "1", color: "Noir / Blanc", size: "41", stock_quantity: 3, price_adjustment: 0 },
      { id: "v1-7", product_id: "1", color: "Noir / Blanc", size: "42", stock_quantity: 2, price_adjustment: 0 },
      { id: "v1-8", product_id: "1", color: "Noir / Blanc", size: "44", stock_quantity: 1, price_adjustment: 0 },
      { id: "v1-9", product_id: "1", color: "Gris / Vert", size: "41", stock_quantity: 2, price_adjustment: 0 },
      { id: "v1-10", product_id: "1", color: "Gris / Vert", size: "43", stock_quantity: 3, price_adjustment: 0 },
      { id: "v1-11", product_id: "1", color: "Gris / Vert", size: "45", stock_quantity: 2, price_adjustment: 0 },
    ],
    images: [
      { id: "i1-1", product_id: "1", image_url: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Max 270 vue de côté", sort_order: 0 },
      { id: "i1-2", product_id: "1", image_url: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Max 270 vue de face", sort_order: 1 },
      { id: "i1-3", product_id: "1", image_url: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Max 270 vue du dessus", sort_order: 2 },
      { id: "i1-4", product_id: "1", image_url: "https://images.unsplash.com/photo-1662410945107-e3e6927e828d?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Max 270 détail semelle", sort_order: 3 },
    ],
  },
  {
    id: "2",
    category_id: "2",
    brand_id: "1",
    name: "Nike Air Force 1 Rose",
    slug: "nike-air-force-1-rose",
    sku: "NK-AF1-ROSE-002",
    main_image_url: "https://images.unsplash.com/photo-1744812441887-8084826a2b04?auto=format&fit=crop&w=800&q=70",
    short_description: "Icône du streetwear féminin disponible en coloris rose exclusif. Confort et style garantis pour toutes vos occasions.",
    description: `La Nike Air Force 1 est une véritable légende du sneaker depuis 1982. Ce coloris rose exclusif apporte une touche féminine et moderne à ce modèle incontournable. Avec sa tige en cuir premium et sa semelle en Air-Sole, elle offre un maintien et un amorti incomparables.\n\nParfaite pour les rues de Libreville, elle s'associe aussi bien à une tenue décontractée qu'à une tenue chic.\n\n**Caractéristiques :**\n- Tige en cuir lisse premium\n- Unité Air-Sole pour l'amorti\n- Design low-top intemporel\n- Disponible en tailles 36 à 42`,
    current_price: 55000,
    old_price: 70000,
    stock_quantity: 8,
    is_featured: true,
    is_new: true,
    is_promo: true,
    status: "active",
    rating: 4.8,
    review_count: 41,
    category: { id: "2", name: "Chaussures Femme", slug: "chaussures-femme", is_active: true, sort_order: 2 },
    brand: { id: "1", name: "Nike", slug: "nike", is_active: true },
    variants: [
      { id: "v2-1", product_id: "2", color: "Rose / Blanc", size: "36", stock_quantity: 2, price_adjustment: 0 },
      { id: "v2-2", product_id: "2", color: "Rose / Blanc", size: "37", stock_quantity: 3, price_adjustment: 0 },
      { id: "v2-3", product_id: "2", color: "Rose / Blanc", size: "38", stock_quantity: 2, price_adjustment: 0 },
      { id: "v2-4", product_id: "2", color: "Blanc pur", size: "37", stock_quantity: 2, price_adjustment: 0 },
      { id: "v2-5", product_id: "2", color: "Blanc pur", size: "38", stock_quantity: 1, price_adjustment: 0 },
      { id: "v2-6", product_id: "2", color: "Blanc pur", size: "39", stock_quantity: 2, price_adjustment: 0 },
    ],
    images: [
      { id: "i2-1", product_id: "2", image_url: "https://images.unsplash.com/photo-1744812441887-8084826a2b04?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Force 1 Rose vue de côté", sort_order: 0 },
      { id: "i2-2", product_id: "2", image_url: "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Force 1 Rose vue de face", sort_order: 1 },
      { id: "i2-3", product_id: "2", image_url: "https://images.unsplash.com/photo-1598978340047-0b311af9de31?auto=format&fit=crop&w=800&q=70", alt_text: "Nike Air Force 1 Rose détail", sort_order: 2 },
    ],
  },
  {
    id: "3",
    category_id: "3",
    brand_id: "1",
    name: "Ensemble Survêtement Nike",
    slug: "ensemble-survetement-nike",
    sku: "NK-SURV-003",
    main_image_url: "https://images.unsplash.com/photo-1540254597053-3901b858d40f?auto=format&fit=crop&w=800&q=70",
    short_description: "Ensemble veste + pantalon de survêtement Nike. Tissu technique respirant, idéal pour le sport ou le quotidien.",
    description: `L'ensemble survêtement Nike allie performance et style pour les hommes actifs au Gabon. Fabriqué en tissu Dri-FIT qui évacue la transpiration, il vous garde au frais même sous la chaleur de Libreville.\n\nLa coupe moderne et décontractée en fait une tenue parfaite aussi bien pour le sport que pour la ville.\n\n**Inclus dans l'ensemble :**\n- Veste zippée avec capuche\n- Pantalon avec ceinture élastique et poches\n\n**Matière :** 100% polyester recyclé`,
    current_price: 45000,
    stock_quantity: 15,
    is_featured: false,
    is_new: true,
    is_promo: false,
    status: "active",
    rating: 4.3,
    review_count: 12,
    category: { id: "3", name: "Vêtements Homme", slug: "vetements-homme", is_active: true, sort_order: 3 },
    brand: { id: "1", name: "Nike", slug: "nike", is_active: true },
    variants: [
      { id: "v3-1", product_id: "3", color: "Noir", size: "S", stock_quantity: 3, price_adjustment: 0 },
      { id: "v3-2", product_id: "3", color: "Noir", size: "M", stock_quantity: 4, price_adjustment: 0 },
      { id: "v3-3", product_id: "3", color: "Noir", size: "L", stock_quantity: 3, price_adjustment: 0 },
      { id: "v3-4", product_id: "3", color: "Noir", size: "XL", stock_quantity: 2, price_adjustment: 0 },
      { id: "v3-5", product_id: "3", color: "Gris", size: "M", stock_quantity: 2, price_adjustment: 0 },
      { id: "v3-6", product_id: "3", color: "Gris", size: "L", stock_quantity: 1, price_adjustment: 0 },
    ],
    images: [
      { id: "i3-1", product_id: "3", image_url: "https://images.unsplash.com/photo-1540254597053-3901b858d40f?auto=format&fit=crop&w=800&q=70", alt_text: "Survêtement Nike ensemble complet", sort_order: 0 },
      { id: "i3-2", product_id: "3", image_url: "https://images.unsplash.com/photo-1644718847248-bdd7b044def9?auto=format&fit=crop&w=800&q=70", alt_text: "Survêtement Nike détail veste", sort_order: 1 },
    ],
  },
  {
    id: "4",
    category_id: "5",
    brand_id: "3",
    name: "iPhone 14 Pro Max 256Go",
    slug: "iphone-14-pro-max-256go",
    sku: "APL-IP14PM-256-004",
    main_image_url: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?auto=format&fit=crop&w=800&q=70",
    short_description: "Le meilleur iPhone jamais conçu. Puce A16 Bionic, Dynamic Island, appareil photo 48 Mpx Pro et écran Super Retina XDR.",
    description: `L'iPhone 14 Pro Max représente le summum de la technologie Apple. Avec sa puce A16 Bionic, il offre des performances inégalées pour toutes vos applications, jeux et tâches professionnelles.\n\nLe Dynamic Island révolutionne la façon dont vous interagissez avec les notifications et les activités en direct. L'appareil photo Pro de 48 Mpx capture des détails extraordinaires même dans les conditions de faible luminosité.\n\n**Caractéristiques clés :**\n- Puce A16 Bionic (processeur le plus rapide sur smartphone)\n- Écran Super Retina XDR 6,7" OLED 120 Hz ProMotion\n- Triple caméra 48 Mpx + ultra grand-angle + téléobjectif 3x\n- Vidéo Cinematic 4K 30 fps\n- Autonomie jusqu'à 29 heures de lecture vidéo\n- iOS 17 pré-installé\n- Résistance à l'eau IP68\n\nLivraison rapide à Libreville et partout au Gabon. Paiement à la livraison disponible.`,
    current_price: 850000,
    old_price: 950000,
    stock_quantity: 4,
    is_featured: true,
    is_new: false,
    is_promo: true,
    status: "active",
    rating: 4.9,
    review_count: 67,
    category: { id: "5", name: "Électroniques", slug: "electroniques", is_active: true, sort_order: 5 },
    brand: { id: "3", name: "Apple", slug: "apple", is_active: true },
    variants: [
      { id: "v4-1", product_id: "4", color: "Violet Intense", size: "256 Go", stock_quantity: 2, price_adjustment: 0 },
      { id: "v4-2", product_id: "4", color: "Noir Sidéral", size: "256 Go", stock_quantity: 1, price_adjustment: 0 },
      { id: "v4-3", product_id: "4", color: "Or", size: "256 Go", stock_quantity: 1, price_adjustment: 0 },
      { id: "v4-4", product_id: "4", color: "Violet Intense", size: "512 Go", stock_quantity: 0, price_adjustment: 80000 },
      { id: "v4-5", product_id: "4", color: "Noir Sidéral", size: "512 Go", stock_quantity: 0, price_adjustment: 80000 },
    ],
    images: [
      { id: "i4-1", product_id: "4", image_url: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?auto=format&fit=crop&w=800&q=70", alt_text: "iPhone 14 Pro Max vue de face", sort_order: 0 },
      { id: "i4-2", product_id: "4", image_url: "https://images.unsplash.com/photo-1680687688158-e9165395ff00?auto=format&fit=crop&w=800&q=70", alt_text: "iPhone 14 Pro Max vue de côté", sort_order: 1 },
      { id: "i4-3", product_id: "4", image_url: "https://images.unsplash.com/photo-1677144646095-ecd95d06cd71?auto=format&fit=crop&w=800&q=70", alt_text: "iPhone 14 Pro Max caméra", sort_order: 2 },
    ],
  },
  {
    id: "5",
    category_id: "5",
    brand_id: "4",
    name: "Samsung Galaxy A54",
    slug: "samsung-galaxy-a54",
    sku: "SAM-A54-256-005",
    main_image_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=70",
    short_description: "Smartphone Samsung Galaxy A54 avec écran Super AMOLED 6,4\", triple caméra 50 Mpx et batterie 5000 mAh.",
    description: `Le Samsung Galaxy A54 est le smartphone idéal pour ceux qui veulent le meilleur rapport qualité-prix au Gabon. Son écran Super AMOLED de 6,4" avec un taux de rafraîchissement de 120 Hz offre une fluidité et une qualité d'image remarquables.\n\nAvec sa triple caméra de 50 Mpx, capturez vos meilleurs moments au Gabon avec une précision et une clarté exceptionnelles.\n\n**Points forts :**\n- Écran Super AMOLED 6,4" 120 Hz\n- Triple caméra : 50 Mpx + 12 Mpx ultra grand-angle + 5 Mpx macro\n- Batterie 5000 mAh avec charge rapide 25W\n- 8 Go RAM + 256 Go stockage\n- Android 13 avec One UI 5.1\n- Résistance à l'eau IP67`,
    current_price: 280000,
    old_price: 320000,
    stock_quantity: 9,
    is_featured: false,
    is_new: true,
    is_promo: true,
    status: "active",
    rating: 4.4,
    review_count: 34,
    category: { id: "5", name: "Électroniques", slug: "electroniques", is_active: true, sort_order: 5 },
    brand: { id: "4", name: "Samsung", slug: "samsung", is_active: true },
    variants: [
      { id: "v5-1", product_id: "5", color: "Blanc Awesome", size: "128 Go", stock_quantity: 3, price_adjustment: -20000 },
      { id: "v5-2", product_id: "5", color: "Noir Awesome", size: "128 Go", stock_quantity: 2, price_adjustment: -20000 },
      { id: "v5-3", product_id: "5", color: "Blanc Awesome", size: "256 Go", stock_quantity: 2, price_adjustment: 0 },
      { id: "v5-4", product_id: "5", color: "Noir Awesome", size: "256 Go", stock_quantity: 2, price_adjustment: 0 },
    ],
    images: [
      { id: "i5-1", product_id: "5", image_url: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=70", alt_text: "Samsung Galaxy A54 face avant", sort_order: 0 },
      { id: "i5-2", product_id: "5", image_url: "https://images.unsplash.com/photo-1707438095940-1eee18e85400?auto=format&fit=crop&w=800&q=70", alt_text: "Samsung Galaxy A54 vue arrière", sort_order: 1 },
    ],
  },
  {
    id: "6",
    category_id: "5",
    brand_id: "5",
    name: "JBL Tune 510BT",
    slug: "jbl-tune-510bt",
    sku: "JBL-T510BT-006",
    main_image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=70",
    short_description: "Casque audio Bluetooth sans fil JBL avec son Pure Bass, 40h d'autonomie et pliable pour une portabilité maximale.",
    description: `Le JBL Tune 510BT est le casque audio parfait pour profiter de votre musique préférée au Gabon. Grâce à la technologie JBL Pure Bass, vous bénéficierez d'un son puissant et équilibré qui vous plongera dans vos morceaux favoris.\n\nAvec 40 heures d'autonomie, il vous accompagne pendant vos déplacements, au bureau, ou lors de vos sorties à Libreville sans vous soucier de la batterie.\n\n**Caractéristiques :**\n- Son JBL Pure Bass signé\n- Bluetooth 5.0 avec portée de 10 m\n- 40h d'autonomie (5h de charge rapide = 2h d'écoute)\n- Microphone intégré pour les appels\n- Design léger et pliable\n- Compatible assistant vocal (Siri, Google)`,
    current_price: 38000,
    old_price: 52000,
    stock_quantity: 20,
    is_featured: false,
    is_new: false,
    is_promo: true,
    status: "active",
    rating: 4.6,
    review_count: 89,
    category: { id: "5", name: "Électroniques", slug: "electroniques", is_active: true, sort_order: 5 },
    brand: { id: "5", name: "JBL", slug: "jbl", is_active: true },
    variants: [
      { id: "v6-1", product_id: "6", color: "Noir", size: "Unique", stock_quantity: 8, price_adjustment: 0 },
      { id: "v6-2", product_id: "6", color: "Blanc", size: "Unique", stock_quantity: 6, price_adjustment: 0 },
      { id: "v6-3", product_id: "6", color: "Bleu", size: "Unique", stock_quantity: 4, price_adjustment: 0 },
      { id: "v6-4", product_id: "6", color: "Rouge", size: "Unique", stock_quantity: 2, price_adjustment: 0 },
    ],
    images: [
      { id: "i6-1", product_id: "6", image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=70", alt_text: "JBL Tune 510BT casque bluetooth", sort_order: 0 },
      { id: "i6-2", product_id: "6", image_url: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=70", alt_text: "JBL Tune 510BT vue de côté", sort_order: 1 },
      { id: "i6-3", product_id: "6", image_url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=70", alt_text: "JBL Tune 510BT sur table", sort_order: 2 },
    ],
  },
  {
    id: "7",
    category_id: "8",
    name: "Sac à Main Élégant",
    slug: "sac-main-elegant",
    sku: "SAC-ELGT-007",
    main_image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=70",
    short_description: "Sac à main en cuir synthétique premium, design moderne et élégant. Compartiments pratiques pour toutes vos essentielles.",
    description: `Ce sac à main élégant est la pièce accessoire indispensable pour la femme moderne au Gabon. Son design contemporain s'adapte à toutes les occasions, du bureau à la soirée en passant par les sorties shopping à Libreville.\n\nFabriqué en cuir synthétique premium de haute qualité, il est à la fois durable et facile d'entretien.\n\n**Détails :**\n- Cuir synthétique premium\n- Fermeture éclair sécurisée\n- 1 compartiment principal + 2 poches intérieures + 1 poche zippée\n- Bandoulière réglable et amovible\n- Dimensions : 30 x 20 x 12 cm\n- Disponible en plusieurs coloris`,
    current_price: 35000,
    stock_quantity: 6,
    is_featured: false,
    is_new: true,
    is_promo: false,
    status: "active",
    rating: 4.2,
    review_count: 18,
    category: { id: "8", name: "Accessoires Femme", slug: "accessoires-femme", is_active: true, sort_order: 8 },
    variants: [
      { id: "v7-1", product_id: "7", color: "Marron", size: "Unique", stock_quantity: 2, price_adjustment: 0 },
      { id: "v7-2", product_id: "7", color: "Noir", size: "Unique", stock_quantity: 3, price_adjustment: 0 },
      { id: "v7-3", product_id: "7", color: "Beige", size: "Unique", stock_quantity: 1, price_adjustment: 0 },
    ],
    images: [
      { id: "i7-1", product_id: "7", image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=70", alt_text: "Sac à main élégant vue de face", sort_order: 0 },
      { id: "i7-2", product_id: "7", image_url: "https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?auto=format&fit=crop&w=800&q=70", alt_text: "Sac à main élégant détail", sort_order: 1 },
      { id: "i7-3", product_id: "7", image_url: "https://images.unsplash.com/photo-1614179689702-355944cd0918?auto=format&fit=crop&w=800&q=70", alt_text: "Sac à main élégant intérieur", sort_order: 2 },
    ],
  },
  {
    id: "8",
    category_id: "7",
    name: "Montre Curren Homme",
    slug: "montre-curren-homme",
    sku: "CUR-MON-H-008",
    main_image_url: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=800&q=70",
    short_description: "Montre homme Curren analogique avec bracelet en acier inoxydable. Élégante et robuste pour toutes vos occasions.",
    description: `La Montre Curren Homme est l'accessoire incontournable pour l'homme élégant et moderne au Gabon. Son design sobre et raffiné s'adapte aussi bien aux tenues décontractées qu'aux tenues professionnelles.\n\nAvec son boîtier en acier inoxydable et son verre minéral résistant aux rayures, elle est conçue pour durer.\n\n**Spécifications :**\n- Mouvement : Quartz japonais de précision\n- Boîtier : Acier inoxydable 316L\n- Cadran : Analogique avec date\n- Verre : Minéral anti-rayures\n- Résistance à l'eau : 3 ATM (éclaboussures)\n- Bracelet : Acier inoxydable avec boucle déployante\n- Diamètre boîtier : 42 mm`,
    current_price: 22000,
    old_price: 30000,
    stock_quantity: 14,
    is_featured: false,
    is_new: false,
    is_promo: true,
    status: "active",
    rating: 4.1,
    review_count: 27,
    category: { id: "7", name: "Accessoires Homme", slug: "accessoires-homme", is_active: true, sort_order: 7 },
    variants: [
      { id: "v8-1", product_id: "8", color: "Argent / Noir", size: "Unique", stock_quantity: 5, price_adjustment: 0 },
      { id: "v8-2", product_id: "8", color: "Or / Blanc", size: "Unique", stock_quantity: 4, price_adjustment: 0 },
      { id: "v8-3", product_id: "8", color: "Noir / Noir", size: "Unique", stock_quantity: 5, price_adjustment: 0 },
    ],
    images: [
      { id: "i8-1", product_id: "8", image_url: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=800&q=70", alt_text: "Montre Curren Homme vue de face", sort_order: 0 },
      { id: "i8-2", product_id: "8", image_url: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=70", alt_text: "Montre Curren Homme au poignet", sort_order: 1 },
      { id: "i8-3", product_id: "8", image_url: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=800&q=70", alt_text: "Montre Curren Homme détail bracelet", sort_order: 2 },
    ],
  },
];

export const mockNewProducts = mockProducts.filter((p) => p.is_new);
export const mockPromoProducts = mockProducts.filter((p) => p.is_promo);
export const mockFeaturedProducts = mockProducts.filter((p) => p.is_featured);
